apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: secretimports.secretgen.carvel.dev
spec:
  group: secretgen.carvel.dev
  names:
    kind: SecretRequest
    listKind: SecretRequestList
    plural: secretimports
    singular: secretimport
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
  additionalPrinterColumns:
  - name: Description
    type: string
    description: Friendly description
    JSONPath: .status.friendlyDescription
  - name: Age
    type: date
    description: Time passed since creation
    JSONPath: .metadata.creationTimestamp
