apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: user-password
spec: {}
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: long-user-password
spec:
  length: 124
