apiVersion: secretgen.k14s.io/v1alpha1
kind: Certificate
metadata:
  name: ca-cert
spec:
  isCA: true
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Certificate
metadata:
  name: app1-cert
spec:
  caRef:
    name: ca-cert
  alternativeNames:
  - app1.svc.cluster.local
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Certificate
metadata:
  name: app2-cert
spec:
  caRef:
    name: ca-cert
  alternativeNames:
  - app2.svc.cluster.local
---
apiVersion: v1
kind: Pod
metadata:
  name: app1
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
spec:
  containers:
  - name: app
    image: docker.io/dkalinin/k8s-simple-app@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
  volumes:
  - name: cert
    secret:
      secretName: app1-cert
  - name: ca
    secret:
      secretName: ca-cert
---
apiVersion: v1
kind: Pod
metadata:
  name: app2
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
spec:
  containers:
  - name: app
    image: docker.io/dkalinin/k8s-simple-app@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
  volumes:
  - name: config
    secret:
      secretName: app2-cert
  - name: ca
    secret:
      secretName: ca-cert
