name: sgc-release

on:
  push:
    tags:
      - "v*"

jobs:
  sgcreleaser:
    name: secretgen controller release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6

      - name: Fetch kctrl
        uses: actions/checkout@v3
        with:
          ref: pkg-authoring
          repository: vmware-tanzu/carvel-kapp-controller
          path: carvel-kapp-controller
          fetch-depth: 0

      - name: Build kctrl
        working-directory: ./carvel-kapp-controller/cli
        run: |
          ls
          ./hack/build.sh
#          set -e -x -u
#          VERSION="v0.38.3"
#
#          # makes builds reproducible
#          export CGO_ENABLED=0
#          LDFLAGS="-X github.com/vmware-tanzu/carvel-kapp-controller/cli/pkg/kctrl/version.Version=$VERSION"
#
#          go mod vendor
#          go mod tidy
#          go fmt ./cmd/... ./pkg/... ./test/...
#
#          go build -ldflags="$LDFLAGS" -trimpath -o kctrl ./cmd/kctrl/...
#          ./kctrl version
#
#          # compile tests, but do not run them: https://github.com/golang/go/issues/15513#issuecomment-839126426
#          # go test --exec=echo ./... >/dev/null
#
#          echo "Success"
#          cp kctrl ../../carvel/kctrl

#      - name: Checkout to publish-package branch
#        uses: actions/checkout@v3
#        with:
#          ref: nh-publish-package

      - name: Run Package build
        working-directory: ./carvel
        run: |
          ls -la
          ./../carvel-kapp-controller/cli/kctrl pkg build create -y -v 1.0.0
            






          
