name: sgc-release

on:
  push:
    tags:
      - "v*"

jobs:
  sgcreleaser:
    name: secretgen controller release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6

      - name: Fetch kctrl
        steps:
          uses: actions/checkout@v3
            with:
              ref: pkg-authoring
              repository: vmware-tanzu/carvel-kapp-controller
          run: |
            pwd
            ls
            cat README.md
            ./hack/build.sh

      - name: Build kctrl
        run: |
          pwd
          ls
          cat README.md

      - name: Run Package build
        run: |
          cd carvel
          ./cli/kctrl pkg build create -y -v 1.0.0
          ls -la
            






          
