name: sgc-release

on:
  push:
    tags:
      - "v*"

jobs:
  sgcreleaser:
    name: secretgen controller release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6

      - name: Fetch kctrl
        uses: actions/checkout@v3
        with:
          ref: pkg-authoring
          repository: vmware-tanzu/carvel-kapp-controller
          path: carvel-kapp-controller

      - name: Build kctrl
        run: |
          pwd
          ls
          cd carvel-kapp-controller/cli
          ls 
          ./hack/build.sh
          ls
          ./kctrl version
          cp kctrl ../../kctrl

      - name: Run Package build
        run: |
          ls -la
          cd carvel
          ./cli/kctrl pkg build create -y -v 1.0.0
          ls -la
            






          
